# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cleanpdf.py']
APP_NAME = "Clean PDF"
DATA_FILES = []
OPTIONS = {'argv_emulation': False,
           'iconfile': 'app1.icns',
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'CFBundleGetInfoString': "Wipe Metadata from pdfs",
               'CFBundleIdentifier': "us.jamescampbell.osx.cleanpdf",
               'CFBundleVersion': "1.1.0",
               'CFBundleShortVersionString': "1.1.0",
               'NSHumanReadableCopyright': u"Copyright © 2019, James Campbell, All Rights Reserved"
           }
           }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
